apiVersion: v1

kind: Service

metadata:

  name: web-httpd
  labels:

    app: httpd

spec:

  ports:

    - nodePort: 30009
      port: 80
      targetPort: 80
  selector:

    app: httpd
    tier: web
  type: NodePort

---

apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: php-pv-claim

  labels:

    app: httpd
spec:

  accessModes:

    - ReadWriteOnce
  resources:

    requests:

      storage: 2Gi

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2

kind: Deployment

metadata:

  name: apache-php
  labels:

    app: httpd

spec:

  selector:

    matchLabels:

      app: httpd

      tier: web
  strategy:

    type: Recreate

  template:

    metadata:

      labels:

        app: httpd

        tier: web
    spec:

      containers:

      - image: vimal13/apache-webserver-php
        name: apache-php
        ports:

        - containerPort: 80

          name: apache-php

        volumeMounts:

        - name: wordpress-persistent-storage

          mountPath: /var/www/html

      volumes:

      - name: wordpress-persistent-storage

        persistentVolumeClaim:

          claimName: php-pv-claim
